### ISSUE TITLE
Bad error: AttributeError: module 'pypugjs' has no attribute 'exceptions'

### ISSUE THREAD

**Issue by mondeja** [kakulukia/pypugjs#15]
* pypugjs version: 5.5.0
* Django version: 2.0.3
* Python version: 3.7.0a4
* Operating System: Linux - Debian 9

### What I Did
Trying to process a file with the function `process_pugjs()` from `pypugjs.ext.html` I get a bad error: 
```
Traceback (most recent call last):
  File "bin/build/html.py", line 68, in <module>
    main()
  File "bin/build/html.py", line 63, in main
    a = process_pugjs(read_f(src), **options)
  File "/usr/local/lib/python3.7/site-packages/pypugjs/ext/html.py", line 178, in process_pugjs
    return compiler.compile()
  File "/usr/local/lib/python3.7/site-packages/pypugjs/compiler.py", line 114, in compile
    self.visit(self.node)
  File "/usr/local/lib/python3.7/site-packages/pypugjs/compiler.py", line 145, in visit
    self.visitNode(node, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypugjs/compiler.py", line 153, in visitNode
    return getattr(self, 'visit%s' % name)(node, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypugjs/compiler.py", line 160, in visitBlock
    self.visit(node)
  File "/usr/local/lib/python3.7/site-packages/pypugjs/compiler.py", line 145, in visit
    self.visitNode(node, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypugjs/compiler.py", line 153, in visitNode
    return getattr(self, 'visit%s' % name)(node, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypugjs/ext/html.py", line 98, in visitExtends
    raise pypugjs.exceptions.CurrentlyNotSupported()
AttributeError: module 'pypugjs' has no attribute 'exceptions'
```

**Comment by kakulukia** [comment]
@mondeja could you give me a stripped down version of the pug file causing this error?

**Comment by kakulukia** [comment]
You are trying to use functionality unsupported by the command line tool. Id like to know what it was to be able to fix it.

**Comment by kakulukia** [comment]
a patched version is uploaded, tho

leave a github star, if it works for you again :)
