### ISSUE TITLE
Too many values to unpack: list flask

### ISSUE THREAD

**Issue by remimarenco** [kakulukia/pypugjs#17]
* pypugjs version: 5.6.0
* Django version: N/A
* Flask version: 1.0.2
* Python version: 3.6.1
* Operating System: MAC OSX

### Description

Hi! Thanks for doing this plugin, it's really cool. I was playing around with it, and I am not sure how to get the index of a list when I am in an iteration loop.

### What I Did

```
each broadie, index in list_broadies
    p Hi!
```
Where list_broadies is an array of Objects,

Produces this error:

> Traceback (most recent call last):
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/tornado-5.0.2-py3.6-macosx-10.11-x86_64.egg/tornado/web.py", line 1520, in _execute
>     result = self.prepare()
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/tornado-5.0.2-py3.6-macosx-10.11-x86_64.egg/tornado/web.py", line 2826, in prepare
>     self.fallback(self.request)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/livereload-2.5.2-py3.6.egg/livereload/server.py", line 114, in __call__
>     WSGIContainer.environ(request), start_response)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Werkzeug-0.14.1-py3.6.egg/werkzeug/wsgi.py", line 826, in __call__
>     return app(environ, start_response)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib

> 
> /python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/Users/rmarenco/Dev/cp_id_wall/cp_id_wall/views.py", line 13, in index
>     return render_template('index.pug', list_broadies=list_broadies_json)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/templating.py", line 135, in render_template
>     context, ctx.app)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/templating.py", line 117, in _render
>     rv = template.render(context)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Jinja2-2.10-py3.6.egg/jinja2/asyncsupport.py", line 76, in render
>     return original_render(self, *args, **kwargs)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Jinja2-2.10-py3.6.egg/jinja2/environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Jinja2-2.10-py3.6.egg/jinja2/environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/Users/rmarenco/Dev/cp_id_wall/venv/lib/python3.6/site-packages/Jinja2-2.10-py3.6.egg/jinja2/_compat.py", line 37, in reraise
>     raise value.with_traceback(tb)
>   File "/Users/rmarenco/Dev/cp_id_wall/cp_id_wall/templates/index.pug", line 40, in top-level template code
>     p Hi!
> ValueError: too many values to unpack (expected 2)

Thanks!

**Comment by kakulukia** [comment]
Well, im not at all familiar with then way the flask version works, but have you tried the official pug docs? https://pugjs.org/language/iteration.html

I know that in the Django version, you automatically have the forloop variable from Django, but since im not working with the flask port myself, i cant help you here. :(
Sorry!

**Comment by kakulukia** [comment]
@remimarenco did you get it to work the way you wanted?
Can we close this and maybe put another hint inside the docs?

**Comment by IlIIIllIlIlllllIIIIlllIlllIllllIlllllll** [comment]
@remimarenco what's the status of this issue atm?

**Comment by remimarenco** [comment]
Sorry I am in vacation currently. I think we can close this for now, and yes putting a hint inside the docs would be great :).
Thanks a lot!
